- README.md
- config/dev.exs
This patch updates the readme to add additional configuration information that
may help the getting started experience for developers and a small configuration
change to the development config.
Upon implementing elixometer I struggled to figure out why my reporter wasn't being
called, neither a custom reporter nor :exometer_report_tty was working.
After routing around in the source I found that you must register your reporter with
both exometer AND elixometer in order for it to work correctly.
This patch hopes to share that knowledge with the community.
> Adds extra information to readme and lowers update_frequency in dev

- lib/elixometer.ex
- mix.exs
- mix.lock
- test/elixometer_test.exs
My use case is tracking quota usage for a third party API, where the usage meter resets daily. I'd planned on resetting my quota counter at the appropriate time with [Quantum](https://github.com/c-rack/quantum-elixir), but soon realized that counter values already reset every 60 seconds by default. So, I made it possible to disable the auto-reset. The change should be non-breaking.
I am curious, though: why is auto-reset the default? AFAICT, Exometer doesn't do this.
> Allow counters that don't automatically reset

- .travis.yml
* fix prompting for hex installation (force hex installed locally beforehand)
* repo errored out build status:
https://travis-ci.org/pinterest/elixometer/builds/100247896
> Notice that the most repo travisci build errored out.

- lib/elixometer.ex
Per build status:
https://travis-ci.org/pinterest/elixometer/builds/100271457
Compiled lib/supervisor.ex
lib/elixometer.ex:288: warning: variable opts is unused
Compiled lib/elixometer.ex
Generated elixometer app
> Fix compiler warning of unused variable

- .travis.yml
- README.md
* Fix code coverage badge url
* Add test execution detail show up on build. It is hard to tell which test failed
> Fix coverall.io badge url; add test execution details

- config/dev.exs
- config/test.exs
- mix.exs
- mix.lock
The community doesn't like having exometer as a dependency since most of
the popular reporters are inside of exometer_core anyway. I removed it
and cleaned up some of the other dependencies as well.
Addresses #19 
@jparise
> Removed exometer as a dependency

- lib/elixometer.ex
. Since process already registered locally as __MODULE__, no need to query for pid.
> Fix Remove inconsistency

- mix.exs
Upgrade all elixir project to use same version as in elixir-thrift:
reference
https://github.com/pinterest/elixir-thrift/commit/12407035ff5fe480ba957c1379d4478ef1099fb5
> Fix upgrade excoveralls to 0.4.5

- README.md
Using the current example in an application causes the following error:
> You have configured application :exometer in your configuration
> file but the application is not available.
I think this is because #20 updated elixometer to depend on
exometer_core instead of exometer, but did not update the README to
configure exometer_core.
> Update README to configure `exometer_core`

- mix.exs
When application is started, it error on :logger.
exometer and other dependency projects uses :lager. 
PR is to start :lager right from the start instead of :logger.
Error message
2015-12-31 14:05:00 =SUPERVISOR REPORT====
Supervisor: {local,'Elixir.Logger.Supervisor'}
Context:    child_terminated
Reason:     normal
Offender:   [{pid,<0.183.0>},{id,'Elixir.Logger.ErrorHandler'},{mfargs,{'Elixir.Logger.Watcher',watcher,[error_logger,'Elixir.Logger.ErrorHandler',{true,false,500},link]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]
> Fix start with :lager instead of :logger

- lib/elixometer.ex
- lib/supervisor.ex
- lib/updater.ex
- lib/utils.ex
- mix.exs
- mix.lock
- test/elixometer_test.exs
When used in code that's called a *lot*, Elixometer's main process can become a bottleneck. I witnessed this in our rate limiter, where we would send quite a few performance metrics through Elixometer, which would negatively affect the 99% response time of the app.
The cause of this is Elixometer's synchronous `gen_server`, which waits until `exometer` responds before returning. This PR creates another `gen_server`, the `Updater` that does the work of notifying exometer. The updater also uses the `po_box` library to ensure its mailbox doesn't overflow. This means that Elixometer can drop messages, but I think that's a better compromise than having it affect your system's performance.
@jparise
> Controlling process

- README.md
- lib/elixometer.ex
- test/elixometer_test.exs
- test/support/test_reporter.ex
E.g. for InfluxDB adapter you can pass in tags via these extra fields.
Would be even more useful if it could be done optionally in every wrapper function, but I wasn't sure how to accomplish that.
> Adds configurable 'extra' options

- lib/elixometer.ex
The `:subscribe_options` configuration entry is documented
as a list, but the fallback value is `true`.  This causes
problems with, e.g., the InfluxDB reporter, which expects
extra subscription options to be a list or `undefined`.
> Use a list as a fallback for `:subscribe_options`

- lib/utils.ex
- test/elixometer_test.exs
Profiling showed a significant amount of time being spent in
Utils.name_to_exometer and to_atom_list. One solution is to convert static
metric names to lists ahead of time, or otherwise manually assembling the
desired list form of the metric. Updater.timer supports this pattern by
avoiding a double conversion, but counter/etc do not. This change should
add support to all metric types.
There is a bit of redundancy now in that Updater.timer still does its check. I
haven't removed it because I'm not sure if there was some reason we always
wanted timer metric names converted in the calling process, rather than in the
registered Updater process.
> Broaden support for pre-computing metric names

- lib/updater.ex
- mix.exs
Elixir 1.4 deprecated bare words, so this removes a bunch of the new compiler warnings. 
```
❯ elixir --version
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.4.0
❯ mix compile --force --warnings-as-errors
Compiling 4 files (.ex)
Generated elixometer app
```
> Added parentheses to get rid of Elixir 1.4 warnings.

- test/elixometer_test.exs
This addresses Elixir 1.4 warnings.
> Add parens to ambiguous function calls

- .travis.yml
- mix.exs
This revises the build matrix so that we test the oldest supported
Elixir version (now 132.0) as well as the newest (currently 1.4.0).
Note that increase in minimum version to Elixir 1.3.0. Due to previous
changes related to our lager version override, we can no longer support
Elixir 1.0.0.
This also removes some unnecessary setup steps; all of the removed
things already happen by default.
> Test our oldest and newest Elixir version pairs

- lib/elixometer.ex
- lib/updater.ex
- test/elixometer_test.exs
To maintain consistency with the Elixir standard library, Elixometer should support all the same time units. These can be viewed at https://hexdocs.pm/elixir/System.html#t:time_unit/0.
I left in support for `:micros` and `:millis` so that this is not a breaking change, but I also made `:microsecond` the default.
> Add support for all Elixir time units

- README.md
- config/config.exs
- lib/elixometer.ex
- lib/updater.ex
- lib/utils.ex
- test/elixometer_test.exs
- test/support/test_reporter.ex
Hello,
This PR introduces two changes:
1. All the names are now transferred as list of binaries, instead of generating atoms at runtime. This is useful for an environment where metrics are built dynamically, preventing the VM from exploding due to atoms not being garbage collected. `exometer` is perfectly fine accepting _lists of terms_ for metric identifiers.
1. New configuration options: 
- `max_messages` - allows fine tuning the `pobox` buffer size
- `formatter` - allows injecting a custom metric name formatting function, useful for legacy systems where metrics have already a naming scheme that needs to be preserved.
Let me know please, if this is good to go 🍻
> Do not generate atoms / custom metrics formatting

- README.md
- lib/utils.ex
- test/elixometer_test.exs
In your config/config.exs you can set {:system, "ENV_VARIABLE_HERE"} to allow the
env to be set with environmental variables supplied on runtime.
```
config :elixometer, env: {:system, "ELIXOMETER_ENV"}
```
> Allow :env to be configurable from env variables

- .travis.yml
Also bump us to the latest 1.4 release (1.4.5).
> Update Travis environment to use OTP 20.0

- config/dev.exs
- config/test.exs
The previous syntax has been deprecated.
> Use keyword lists for lager configuration

- .travis.yml
- lib/elixometer.ex
- test/elixometer_test.exs
- test/support/test_reporter.ex
- test/test_helper.exs
In addition to bumping Travis's Elixir version to 1.5.1, this change adds
support for an Elixir 1.5 change to `@on_definition`. From the [Elixir 1.5
release notes](https://github.com/elixir-lang/elixir/blob/v1.5/CHANGELOG.md):
> The `on_definition/6` callback now receives `body` wrapped in a keyword
> list, such as `[do: body]`. This solves a bug where it was impossible to
> distinguish between a bodyless clause and a function that returns `nil`.
> Support Elixir 1.5

- test/elixometer_test.exs
- test/support/test_reporter.ex
I'm adding a separate PR to tackle the fact that we were swallowing datapoint information in the `testReporter`. This allows for more robust testing of my datapoints blacklist feature. 
I'll merge this first into that branch once it's reviewed, then we can proceed to merge #91 into master
> Add support for datapoints in subscriptions in test reporter

- README.md
- lib/elixometer.ex
- test/elixometer_test.exs
- test/support/test_reporter.ex
Fixes #37 (Use mechanism to whitelist subscriptions)
Done criteria:
> Add filtering of (metric, datapoint) from config blacklist on subscribe

- lib/elixometer.ex
- test/elixometer_test.exs
Hello,
This PR fixes #89 by  adding two new methods for handling wildcard keys: `get_metric_values/1` and `get_metric_values/2`.
> Add wildcard key support

- lib/elixometer.ex
- test/elixometer_test.exs
bind_quoted binds variables to the results of the quoted values and
prepends those to the new quoted expression. Then uses the variables
in the remainder of the quoted expression. This caused the body to be
evaluated before the timer and the timer would only measure
fn -> result end.
Closes #100
> Fix timed function attribute to time body

- README.md
The syntax used in the example for `excluded_datapoints` is not valid: `:999` raises SyntaxError.
This PR fixes the example to use the expected syntax for "numeric" datapoints (integers instead of atoms).
> Fix `excluded_datapoints` README example.

- mix.exs
```
warning: outdented heredoc line. The contents inside the heredoc should be indented at the same level as the closing """. The following is forbidden:
def text do
"""
contents
"""
end
Instead make sure the contents are indented as much as the heredoc closing:
def text do
"""
contents
"""
end
The current heredoc line is indented too little
/Users/asummers/Code/MyProject/deps/elixometer/mix.exs:51
```
Not sure what it was mad at, exactly, but this seems to fix it.
> Fix 1.6 heredoc warning.

- README.md
- lib/elixometer.ex
- lib/formatter.ex
- lib/updater.ex
- lib/utils.ex
- test/elixometer_test.exs
Hi!
We've found that when attempting to build releases using Distillery, it barfs when trying to use a function ref as a config value.
This PR adds a behaviour so that anyone who wants to add a custom formatter module can do so safely.
> Use Module for configuring formatter instead of function ref

- .travis.yml
- mix.exs
As we prepare for a new release, it's a good time to bump our minimum
required Elixir version. 1.5 is a good baseline as its what a number of
our dependencies now require.
> Require Elixir 1.5 or later

- .markdownlint.json
- CHANGELOG.md
See: https://keepachangelog.com/en/1.0.0/
Also add a small local markdownlint configuration file that ignores
duplicate headers (for compatibility with the above).
> Switch to the "Keep a Changelog" format

- test/elixometer_test.exs
In our gauges test, we compare the results of `exometer.get_values/1` to
`Elixometer.get_metric_values/1`. Because these two functions are called
back-to-back, they run at slightly different times (the second just
after the first). The returned metric values include a time counter
value named `:ms_since_reset` which can differ between the two calls
when they "span" the millisecond boundary, making this test occasionally
fail.
As a fix, strip these entries from the values lists before comparing
them because they are not a very important part of what we're testing.
> Compare values ignoring :ms_since_reset entries

- .travis.yml
Use a more modern OTP 21 release and test older Elixir versions using
OTP 19.3.
> Update the OTP releases used in the test matrix

- README.md
- lib/elixometer.ex
- test/elixometer_test.exs
If you want to avoid having to aggregate each different datapoint for each metric, you can use `report_bulk: true` in your reporters, like so: 
```
config :exometer_core,
report: [
reporters: [
{ExometerTest.Reporter, [report_bulk: true]}
]
],
update_frequency: :timer.seconds(5)
```
But in order for that to work, the subscription for each datapoint needs to be given at one time, as opposed to separate subscriptions. This allows that, by allowing the configuration option `bulk_subscribe: true`
> feat: allow a bulk subscription, to get all metrics at once.

- mix.lock
This fixes :honor_cipher_order-related errors when run against
Erlang/OTP 22.1. (benoitc/hackney#589)
Also update ssl_verify_fun to version 1.1.5 while I'm here.
> Update hackney to version 1.15.2

- .github/workflows/ci.yml
The latest version (v1.2.0) now supports the full range of Elixir/OTP
versions going back to OTP 17 and Elixir 1.0.
> Modernize GitHub Actions workflow

- .github/workflows/ci.yml
This requires us to drop OTP 20.3 unless we want to build out a fancy
matrix, which probably isn't worth it.
Also pin actions/setup-elixir to any v1 version. We expect compatibility
along this entire semantic version tag, and this ensures we'll continue
to pick up minor version updates.
And lastly, remove explicit rebar and hex installation steps. These are
already handled by actions/setup-elixir.
> Add Elixir 1.10 to the testing matrix

- .github/workflows/ci.yml
- lib/elixometer.ex
Elixir 1.11 now enforces keys to be atoms in Keyword.keys/1, so also
update a place where we were making that assumption.
> Add Elixir version 1.11 to the testing matrix

- test/elixometer_test.exs
- test/test_helper.exs
We already require Elixir 1.5 or later so this version check is no
longer needed.
> Remove the "Elixir 1.5" test tag support
